build_info: 'Gigantum Client :: 2020-01-10 :: b96e775c'
created_on: '2020-01-12T22:55:50.036249'
description: Short course on parallel programming for data science.
id: b782c09d2e934dbe8d6630f211fe797e
name: inpe-parallel-data-science
schema: 2
